# Special .cirrus.yml file to test combination of AIO/DIO features.  WIP.

env:
  # accelerate initial clone
  CIRRUS_CLONE_DEPTH: 1

task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-12-2
  peek_script:
    - uname -a
    - find /
    - du -hs /*
    - mount
