task:
  name: macOS
  osx_instance:
    image: catalina-base
  install_script:
    - cpan -T IPC::Run
  build_script:
    - export PERL5LIB=~/perl5/lib/perl5
    - ./configure --enable-cassert --enable-debug --enable-tap-tests --without-readline
    - make -s -j4
  test_script:
    - export PERL5LIB=~/perl5/lib/perl5
    - make -s check || ( for F in ` find . -name initdb.log -o -name regression.diffs ` ; do echo === $F === ; head -1000 $F ; done ; exit 1 )

task:
  name: Windows
  windows_container:
    image: cirrusci/windowsservercore:cmake
  install_script:
    - choco install -y winflexbison activeperl diffutils
    - rename c:\ProgramData\chocolatey\bin\win_flex.exe flex.exe
    - rename c:\ProgramData\chocolatey\bin\win_bison.exe bison.exe
  build_script:
    - SET PATH=%PATH%;C:\Perl64\bin
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"'
    - perl buildsetup.pl
    - msbuild pgsql.sln
  test_script:
    - SET PATH=%PATH%;C:\Perl64\bin
    - cd src\tools\msvc && vcregress check
