freebsd_instance:
  image_family: freebsd-12-1

task:
  install_script:
    pkg install -y gmake readline perl5 bison
  create_user_script:
    - pw usreadd postgres
    - chown -R postgres:postgres .
  build_script:
    su postgres -c ./configure --enable-cassert --enable-debug --with-includes=/usr/local/include --with-libs=/usr/local/lib && gmake -s
  test_script:
    su postgres -c gmake -s check
