freebsd_instance:
  image_family: freebsd-12-1

task:
  install_script: pkg install -y gmake readline perl5 bison
  script: ./configure --enable-cassert --enable-debug --with-includes=/usr/local/include --with-libs=/usr/local/lib && gmake -s && gmake -s check || cat src/test/regress/log/initdb.log 
