#  appveyor.yml
install:
  - cinst winflexbison
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

before_build:
  - rename c:\ProgramData\chocolatey\bin\win_flex.exe flex.exe
  - rename c:\ProgramData\chocolatey\bin\win_bison.exe bison.exe
  - perl buildsetup.pl

build:
  project: pgsql.sln

before_test:
  - 'perl -p -i.bak -e "s/^test: tablespace/#test: tablespace/" src/test/regress/serial_schedule'
  - 'perl -p -i.bak -e "s/^test: tablespace/#test: tablespace/" src/test/regress/parallel_schedule'

test_script:
  - cd src\tools\msvc && vcregress check

on_failure:
  - perl dumpregr.pl

configuration:
  - Release
EOF

cat <<EOF > dumpregr.pl
use strict;
use warnings FATAL => qw(all);

use File::Find;

my $Target = "regression.diffs";

find(\&dump, "src");

sub dump {
  if ($_ eq $Target) {
    my $path = $File::Find::name;
    print "=== $path ===\n";
    open(my $fh, "<", $_) || die "wtf";
    while (my $line = <$fh>) {
      print $line;
      if ($. > 1000) { last; }
    }
  }
}

