image:
  - Ubuntu
  - Visual Studio 2017

for:
  -
    matrix:
      only:
        - image: Ubuntu
      install:
        - sudo apt-get install gdb libipc-run-perl libperl-dev libpython-dev tcl-dev libldap2-dev libicu-dev docbook-xml docbook-xsl libxml2-utils xsltproc krb5-admin-server krb5-kdc krb5-user slapd ldap-utils libssl-dev
      before_build:
        - echo '/tmp/%e-%s-%p.core' | sudo tee /proc/sys/kernel/core_pattern
      build: ./configure --prefix=$HOME/install --enable-debug --enable-cassert --enable-tap-tests --with-tcl --with-python --with-perl --with-ldap --with-openssl --with-gssapi --with-icu && echo "COPT=-Wall -Werror" > src/Makefile.custom && make -j4 all contrib docs && make install
      test_script: make check-world
      on_failure:
        - for f in $(find . -name regression.diffs) ; do echo "========= Contents of $f" ; head -1000 $f ; done
        - for f in $(find . -name install.log) ; do echo "========= Contents of $f" ; tail -100 $f ; done
        - |
    for corefile in $(find /tmp/ -name '*.core' 2>/dev/null) ; do
      binary=$(gdb -quiet -core $corefile -batch -ex 'info auxv' | grep AT_EXECFN | perl -pe "s/^.*\"(.*)\"\$/\$1/g")
      echo dumping $corefile for $binary
      gdb --batch --quiet -ex "thread apply all bt full" -ex "quit" $binary $corefile
    done

  -
    matrix:
      only:
        - image: Visual Studio 2017
    install:
      - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
      - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64'
      - SET PATH=%PATH%;C:\msys64\usr\bin
    before_build:
      - perl buildsetup.pl
    build:
      project: pgsql.sln
    test_script:
      - cd src\tools\msvc && vcregress check
    on_failure:
      - perl dumpregr.pl
    configuration:
      - Debug
