#  appveyor.yml

clone_depth: 1

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64'
  - SET PATH=%PATH%;C:\msys64\usr\bin
  - cpan App::cpanminus
  - cpanm --force IPC::Run

before_build:
  - perl buildsetup.pl
  - copy windows_build_config.pl src\tools\msvc\config.pl

build:
  parallel: true
  project: pgsql.sln

test_script:
  - perl src\tools\msvc\install.pl tmp_install
  - cd src\tools\msvc && vcregress check parallel
  - cd src\tools\msvc && vcregress bincheck

on_failure:
  - perl dumpregr.pl

configuration:
